### PR TITLE
fix switch id between jitsi and bbb

### PR DESCRIPTION
**Pull request by Dan33l**
I didn't know if update about dates was required. 
It wasn't clear to me what the date is relative to.

### CODE REVIEW

**Comment by Dan33l** [comment]
Hum something looks strange.
When i hit to link related to jitsi, my browser(Firefox) show the section named `Similaire à`.

**Comment by Dan33l** [comment]
So you probably can close this PR.

**Comment by bzg** [comment]
Not yet :) I see the same strange behavior, trying to track this right now.

**Comment by bzg** [comment]
Fixed with a workaround, I'll investigate more later on.  Thanks for reporting this annoying bug.

**Pull request closed without merging**
